version: '3.1'

services:
  app: &app
    image: yonikim/data-verify
    tmpfs:
      - /tmp

  node: &node
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - public:/app/server/src/public
      - build:/app/server/build
      - client_node_modules:/app/client/node_modules
      - server_node_modules:/app/server/node_modules
    environment:
      - NODE_ENV=development

  shell:
    <<: *node
    command: /bin/bash
    ports:
      - '8000:8000'

  server:
    <<: *node
    command: yarn run dev
    ports:
      - '8000:8000'

volumes:
  node_modules:
  public:
  build:
  client_node_modules:
  server_node_modules:
